### ISSUE TITLE
Please make a dart:io variant

### ISSUE THREAD

**Issue by stevenroose** [jwashin/jsonrpc2-dart#1]
Currently, the jsonrpc2 client is only usable from the browser. Please add a way to use it from command line as well.

**Comment by jwashin** [comment]
This is a reasonable request, and probably not too difficult to implement. It'll be in the next update.

**Comment by jwashin** [comment]
I have committed an implementation here in lib/jsonrpc_io_client.dart. I refactored the non-http-specific code into client_base, so other transports can probably be done similarly. The io implementation has the same interface as the dart:http implementation. Let me know if it suits.

**Comment by stevenroose** [comment]
I did not try it out, but it seems to be perfect! Nice work!

**Comment by jwashin** [comment]
This is available in release 0.9.5.
