### ISSUE TITLE
How can i add headers to a request?

### ISSUE THREAD

**Issue by calebgrimah** [jwashin/jsonrpc2-dart#4]

**Comment by jwashin** [comment]
It's probably easiest to make your own ServerProxy descendant. 

Look in lib/jsonrpc_client.dart

Around line 42 is where HTTP request headers are set.

**Comment by jwashin** [comment]
Since 3.0.0, the example package:http client supports custom headers. https://github.com/jwashin/jsonrpc2-dart/blob/master/example/jsonrpc_http_client.dart.
